[
  {
    "title": "Anika",
    "age": 22,
    "height": 160,
    "price": 4800,
    "location": "Bangladesh",
    "desc": "Service available, satisfaction guaranteed. Per night rate 9100.",
    "images_blurred": ["https://yourhost.com/anika1_blur.jpg","https://yourhost.com/anika2_blur.jpg"],
    "images_clear": ["https://yourhost.com/anika1.jpg","https://yourhost.com/anika2.jpg"],
    "phone": "+8801712341001",
    "instagram": "not known",
    "facebook": "not known"
  },
  {
    "title": "Mahi",
    "age": 25,
    "height": 170,
    "price": 5500,
    "location": "Bangladesh",
    "desc": "Service available, satisfaction guaranteed. Per night rate 10200.",
    "images_blurred": ["https://yourhost.com/mahi1_blur.jpg","https://yourhost.com/mahi2_blur.jpg"],
    "images_clear": ["https://yourhost.com/mahi1.jpg","https://yourhost.com/mahi2.jpg"],
    "phone": "+8801812341002",
    "instagram": "not known",
    "facebook": "not known"
  },
  {
    "title": "Tania",
    "age": 23,
    "height": 165,
    "price": 4200,
    "location": "Bangladesh",
    "desc": "Service available, satisfaction guaranteed. Per night rate 8500.",
    "images_blurred": ["https://yourhost.com/tania1_blur.jpg","https://yourhost.com/tania2_blur.jpg"],
    "images_clear": ["https://yourhost.com/tania1.jpg","https://yourhost.com/tania2.jpg"],
    "phone": "+8801912341003",
    "instagram": "not known",
    "facebook": "not known"
  },
  {
    "title": "Rifat",
    "age": 28,
    "height": 177,
    "price": 6900,
    "location": "Bangladesh",
    "desc": "Service available, satisfaction guaranteed. Per night rate 11800.",
    "images_blurred": ["https://yourhost.com/rifat1_blur.jpg","https://yourhost.com/rifat2_blur.jpg"],
    "images_clear": ["https://yourhost.com/rifat1.jpg","https://yourhost.com/rifat2.jpg"],
    "phone": "+8801712341004",
    "instagram": "not known",
    "facebook": "not known"
  },
  {
    "title": "Sadia",
    "age": 19,
    "height": 158,
    "price": 3500,
    "location": "Bangladesh",
    "desc": "Service available, satisfaction guaranteed. Per night rate 7800.",
    "images_blurred": ["https://yourhost.com/sadia1_blur.jpg","https://yourhost.com/sadia2_blur.jpg"],
    "images_clear": ["https://yourhost.com/sadia1.jpg","https://yourhost.com/sadia2.jpg"],
    "phone": "+8801812341005",
    "instagram": "not known",
    "facebook": "not known"
  },
  {
    "title": "Nabila",
    "age": 26,
    "height": 172,
    "price": 6000,
    "location": "Bangladesh",
    "desc": "Service available, satisfaction guaranteed. Per night rate 11000.",
    "images_blurred": ["https://yourhost.com/nabila1_blur.jpg","https://yourhost.com/nabila2_blur.jpg"],
    "images_clear": ["https://yourhost.com/nabila1.jpg","https://yourhost.com/nabila2.jpg"],
    "phone": "+8801912341006",
    "instagram": "not known",
    "facebook": "not known"
  },
  {
    "title": "Samira",
    "age": 21,
    "height": 161,
    "price": 4700,
    "location": "Bangladesh",
    "desc": "Service available, satisfaction guaranteed. Per night rate 9300.",
    "images_blurred": ["https://yourhost.com/samira1_blur.jpg","https://yourhost.com/samira2_blur.jpg"],
    "images_clear": ["https://yourhost.com/samira1.jpg","https://yourhost.com/samira2.jpg"],
    "phone": "+8801712341007",
    "instagram": "not known",
    "facebook": "not known"
  },
  {
    "title": "Mim",
    "age": 24,
    "height": 166,
    "price": 5000,
    "location": "Bangladesh",
    "desc": "Service available, satisfaction guaranteed. Per night rate 9800.",
    "images_blurred": ["https://iili.io/CUSCon1.png","https://iili.io/CUSC7up.png","https://iili.io/CUSCquV.png"],
    "images_clear": ["https://iili.io/CUSCxMF.png","https://iili.io/CUSCBwB.png"],
    "phone": "+8801812341008",
    "instagram": "not known",
    "facebook": "not known"
  },
  {
    "title": "Shaila",
    "age": 30,
    "height": 175,
    "price": 6500,
    "location": "Bangladesh",
    "desc": "Service available, satisfaction guaranteed. Per night rate 11500.",
    "images_blurred": ["https://yourhost.com/shaila1_blur.jpg","https://yourhost.com/shaila2_blur.jpg"],
    "images_clear": ["https://yourhost.com/shaila1.jpg","https://yourhost.com/shaila2.jpg"],
    "phone": "+8801912341009",
    "instagram": "not known",
    "facebook": "not known"
  },
  {
    "title": "Ruma",
    "age": 18,
    "height": 154,
    "price": 3000,
    "location": "Bangladesh",
    "desc": "Service available, satisfaction guaranteed. Per night rate 7200.",
    "images_blurred": ["https://yourhost.com/ruma1_blur.jpg","https://yourhost.com/ruma2_blur.jpg"],
    "images_clear": ["https://yourhost.com/ruma1.jpg","https://yourhost.com/ruma2.jpg"],
    "phone": "+8801712341010",
    "instagram": "not known",
    "facebook": "not known"
  }
  // Continue adding more unique names up to as many as you need
]
